#in real project api keys and other sensitive data would be stored as env variables
openweathermap:
  apikey: 2823af86a678bf73da77019141f07859
  host: https://api.openweathermap.org
  path: /data/2.5/weather
  units: metric

ipinfo:
  apikey: 4caa891868c519

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/weather_service_db
    driver-class-name: org.h2.Driver
    username: weather_service
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
